// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xttdsjofdyqazgopjuqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0dGRzam9mZHlxYXpnb3BqdXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNjEyMjcsImV4cCI6MjA1NTkzNzIyN30.pJSPwVLZZptwaM_I8vHSBjvaHPGbNorJqhNSDMGiLb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);